version: '2.0'

services:

  db:
    image: mysql:5.7.35
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    enviroment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123

    jupyter:
      image: jupyter/base-notebook
      ports:
         - 8888:8888

 volumes:
   db_data: